In [1]:
import json
import pandas as pd
from pandas import DataFrame

In [2]:
features = open("features.json",)
data_dict=json.load(features)

In [3]:
def time_diff(features):
    for ip in features:
        for i in range(len(features[ip])):
            log_time=list(features[ip][i]["log_time"])
            if(i==0):
                features[ip][i]["time_diff"]=-1
            else:
                if((log_time[0]-features[ip][i-1]["log_time"][0])<0):
                    features[ip][i]["time_diff"]=-1
                else:
                    time_diff=0
                    if((log_time[2]-features[ip][i-1]["log_time"][2])<0):
                        log_time[2]+=60
                        log_time[1]-=1
                    time_diff+=log_time[2]-features[ip][i-1]["log_time"][2]
                    if((log_time[1]-features[ip][i-1]["log_time"][1])<0):
                        log_time[1]+=60
                        log_time[0]-=1
                    time_diff+=(log_time[1]-features[ip][i-1]["log_time"][1])*60
                    time_diff+=(log_time[0]-features[ip][i-1]["log_time"][0])*3600
                    if(time_diff<0):
                        features[ip][i]["time_diff"]=-1
                    else:
                        features[ip][i]["time_diff"]=time_diff
    return features

In [6]:
data_dict=time_diff(data_dict)

In [7]:
l_ip=[]
l_lon=[]
l_lat=[]
l_time=[]
l_time_diff=[]
l_inst=[]
l_url=[]
l_response=[]
l_weight=[]
for i in data_dict.keys():
    for log in data_dict[i]:
        l_ip.append(i)
        l_lat.append(log["coords"][0])
        l_lon.append(log["coords"][1])
        l_time.append(log["log_time"])
        l_time_diff.append(log["time_diff"])
        l_inst.append(log["instruction"])
        l_url.append(log["url"])
        l_response.append(log["response"])
        l_weight.append(log["response_weight"])

In [8]:
for i in range(len(l_time)):
    l_time[i]=l_time[i][0]

In [9]:
l_ip=pd.Series(l_ip)
l_lat=pd.Series(l_lat)
l_lon=pd.Series(l_lon)
l_time=pd.Series(l_time)
l_inst=pd.Series(l_inst)
l_url=pd.Series(l_url)
l_response=pd.Series(l_response)
l_weight=pd.Series(l_weight)

In [12]:
frame = {"IP": l_ip,"Lat":l_lat,"Lon":l_lon,"Time":l_time,"Time Diff":l_time_diff,"Instruction":l_inst,"URL":l_url,"Response":l_response,"Weight":l_weight}
data=DataFrame(frame)

In [13]:
data

,IP,Lat,Lon,Time,Time Diff,Instruction,URL,Response,Weight
0,47.76.35.19,22.3193,114.1690,6,-1,HEAD,/fr/pag492/explora-platges-i-ports-2/id12/les-...,301,4840
1,47.76.35.19,22.3193,114.1690,6,1,HEAD,/fr/pag492/explora-platges-i-ports-2/id12/les-...,200,5223
2,47.76.35.19,22.3193,114.1690,6,5,HEAD,/fr/pag492/explora-platges-i-ports-2/id12/les-...,301,4840
3,47.76.35.19,22.3193,114.1690,6,1,HEAD,/fr/pag492/explora-platges-i-ports-2/id12/les-...,200,5260
4,47.76.35.19,22.3193,114.1690,6,1,GET,/fr/pag492/explora-platges-i-ports-2/id12/les-...,301,661
...,...,...,...,...,...,...,...,...,...
1077388,64.124.8.96,33.2749,-111.8870,2,1,GET,/media/site1/cache/images/port-aiguadolc-1.jpg...,200,278950
1077389,98.64.96.26,52.3667,4.9000,11,-1,GET,/nl/pl330/nieuws/kalender/id1113/he-mort-el-po...,404,7423
1077390,98.64.96.26,52.3667,4.9000,11,27,GET,/nl/pl330/nieuws/kalender/id1113/he-mort-el-po...,404,2815
1077391,90.74.194.156,39.5638,-0.3368,11,-1,GET,/media/site1/cache/images/dji-0077-2-redim-enc...,200,227390
1077392,90.74.194.156,39.5638,-0.3368,11,10,GET,/media/site1/cache/images/sitges-230704-chirin...,200,2013931